# 第14週 社群網路分析

### Author: 蔡少懷、游兆愷、秦苡軒、陳侑萱、呂育真、李圯(音同怡)瀞、洪唯瑄、陳志翔
### 資料來源: 文字平台收集PTT日本旅遊版版
### 資料集: japan.csv
### 關鍵字: "東京"
### 資料時間: 2023/05/01 ~ 2023/05/21
### 資料筆數: 共 38 篇文章、300 篇回文

#### 因為疫情漸漸趨緩，許多國家開放旅遊，其中以日本為最多台灣人去的地方，因此本次讀書會藉由文字平台下載PTT日本旅遊版五月份到目前為止的文章，討論日旅版上關於東京的發文風向進行網路分析。

In [135]:
#大家好，我們是第一組，我們針對PTT日旅板五月份的發文做社群網路分析。
#因為疫情漸漸趨緩，許多國家開放旅遊，其中以日本為最多台灣人去的地方，因此本次讀書會藉由文字平台下載PTT日本旅遊版五月份到目前為止的文章，討論日旅版上關於東京的發文風向進行網路分析。

In [98]:
! pip install pyvis networkx pandas numpy #在colab下載用到的套件

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pyvis in /usr/local/lib/python3.10/dist-packages (0.3.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (3.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (1.22.4)
Requirement already satisfied: ipython>=5.3.0 in /usr/local/lib/python3.10/dist-packages (from pyvis) (7.34.0)
Requirement already satisfied: jinja2>=2.9.6 in /usr/local/lib/python3.10/dist-packages (from pyvis) (3.1.2)
Requirement already satisfied: jsonpickle>=1.4.1 in /usr/local/lib/python3.10/dist-packages (from pyvis) (3.0.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2022.7.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.10/dist-packages (from ipython>=5.3.0->pyvis) (67.7.2)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.10/dist-packages (from ipython>=5.3.0->pyvis) (0.18.2)
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython>=5.3.0->pyvis) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.10/dist-packages (from ipython>=5.3.0->pyvis) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.10/dist-packages (from ipython>=5.3.0->pyvis) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from ipython>=5.3.0->pyvis) (3.0.38)
Requirement already satisfied: pygments in /usr/local/lib/python3.10/dist-packages (from ipython>=5.3.0->pyvis) (2.14.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.10/dist-packages (from ipython>=5.3.0->pyvis) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.10/dist-packages (from ipython>=5.3.0->pyvis) (0.1.6)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython>=5.3.0->pyvis) (4.8.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2>=2.9.6->pyvis) (2.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython>=5.3.0->pyvis) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython>=5.3.0->pyvis) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.3.0->pyvis) (0.2.6)

In [99]:
import pandas as pd
import numpy as np
import pyvis
import networkx as nx
from pyvis import network as net
import IPython
from IPython.display import display, HTML

In [100]:
raw_data = pd.read_csv('./japan.csv')
raw_data = raw_data[raw_data.artComment != '[]']
raw_data = raw_data.sample(round(raw_data.shape[0]/4))
print(raw_data.shape)
raw_data.head()

(38, 11)

,system_id,artUrl,artTitle,artDate,artPoster,artCatagory,artContent,artComment,e_ip,insertedDate,dataSource
36,37,https://www.ptt.cc/bbs/Japan_Travel/M.16833962...,[資訊]20230506JX803懶人包(暫定),2023-05-07 02:03:39,UncleRed,Japan_Travel,遠因跟基礎知識部分\n\n1.5/6成田機場大風，許多班機重飛或是轉降其他機場\n (另，...,"[{""cmtStatus"": ""推"", ""cmtPoster"": ""chen210121"",...",None,2023-05-09 01:51:39,ptt
49,50,https://www.ptt.cc/bbs/Japan_Travel/M.16835337...,[問題]帶父母第一次東京自助八天,2023-05-08 16:14:57,adychen1982,Japan_Travel,大家好：\n\n 自己是有單獨自助關西的經驗，但東京是第一次。\n\n 而且第一次就帶了...,"[{""cmtStatus"": ""→"", ""cmtPoster"": ""kuku321"", ""c...",115.165.214.2,2023-05-09 01:51:45,ptt
160,161,https://www.ptt.cc/bbs/Japan_Travel/M.16845877...,[問題]迪士尼好夥伴飯店購買迪士尼門票,2023-05-20 21:02:41,skw15,Japan_Travel,各位大大好\n\n我跟家人將在5/25~5/30去日本東京旅遊\n\n頭幾天會住在東京灣東方...,"[{""cmtStatus"": ""→"", ""cmtPoster"": ""leejones"", ""...",36.227.196.88,2023-05-21 02:06:14,ptt
81,82,https://www.ptt.cc/bbs/Japan_Travel/M.16838571...,九州自駕11月,2023-05-12 10:05:39,zonapha,Japan_Travel,去日本多次都是電車但是東京大阪等大城市\n\n這次是去沒去過的九州\n\n請各位大大幫我看行...,"[{""cmtStatus"": ""→"", ""cmtPoster"": ""borriss"", ""c...",39.10.10.157,2023-05-13 02:01:31,ptt
93,94,https://www.ptt.cc/bbs/Japan_Travel/M.16840297...,[問題]住宿選擇之深夜的東京藥妝店,2023-05-14 10:02:52,shin761124,Japan_Travel,以往去東京首選一定是新宿歌舞伎町，白天跑行程，深夜回新宿吃宵夜買藥妝都方便，但隨著時間增長有...,"[{""cmtStatus"": ""推"", ""cmtPoster"": ""tsuneo"", ""cm...",223.138.11.203,2023-05-15 01:49:21,ptt

In [101]:
#parse comment
def getComtInfo(com):
  cmters,cmt_statuss = [],[]
  com = eval(com)
  for i in com:
    print(i)
    cmters.append(i['cmtPoster'])
    cmt_statuss.append(i['cmtStatus'])
  return pd.Series([cmters, cmt_statuss])

raw_data[['artComter','artStatus']] = raw_data['artComment'].apply(lambda r: getComtInfo(r))

{'cmtStatus': '推', 'cmtPoster': 'chen210121', 'cmtContent': ':高調', 'cmtDate': '2023-05-07 02:05:00'}
{'cmtStatus': '推', 'cmtPoster': 'kyonyuumania', 'cmtContent': ':感謝分享', 'cmtDate': '2023-05-07 02:06:00'}
{'cmtStatus': '推', 'cmtPoster': 'debby1993', 'cmtContent': ':據傳803暫定8:00飛？目前乘客發睡袋睡機場地板', 'cmtDate': '2023-05-07 02:07:00'}
{'cmtStatus': '→', 'cmtPoster': 'soulXdancer', 'cmtContent': ':機上罵罵而已沒暴動真是奇蹟', 'cmtDate': '2023-05-07 02:08:00'}
{'cmtStatus': '→', 'cmtPoster': 'shlee', 'cmtContent': ':暴動也沒辦法飛啊也只能罵一罵發洩一下了', 'cmtDate': '2023-05-07 02:08:00'}
{'cmtStatus': '推', 'cmtPoster': 'YYZZKK', 'cmtContent': ':補充極度精簡版懶人包', 'cmtDate': '2023-05-07 02:08:00'}
{'cmtStatus': '推', 'cmtPoster': 'mithralin', 'cmtContent': ':我香草航空那次也沒有人暴動，可能是LCC乘客比較能', 'cmtDate': '2023-05-07 02:10:00'}
{'cmtStatus': '推', 'cmtPoster': 'mithralin', 'cmtContent': ':體諒成本因素(?)，不過有人爭取下才有飲料和早餐', 'cmtDate': '2023-05-07 02:11:00'}
{'cmtStatus': '推', 'cmtPoster': 'purevision', 'cmtContent': ':聽說來回機票全退（？', 'cmtDate': '2023-05-07 02:12:00'}
{'cmtStatus': '→', 'cmtPoster': 'er5820', 'cmtContent': ':睡不到5小時隔天一定很精彩', 'cmtDate': '2023-05-07 02:14:00'}
{'cmtStatus': '推', 'cmtPoster': 'spw050693', 'cmtContent': ':推懶人包解釋', 'cmtDate': '2023-05-07 02:14:00'}
{'cmtStatus': '推', 'cmtPoster': 'encorea84459', 'cmtContent': ':803旅客推精闢懶人包', 'cmtDate': '2023-05-07 02:14:00'}
{'cmtStatus': '推', 'cmtPoster': 'chinick1478', 'cmtContent': ':Push', 'cmtDate': '2023-05-07 02:16:00'}
{'cmtStatus': '推', 'cmtPoster': 'debby1993', 'cmtContent': ':800/801應該是用同組組員來回？只是delay造成超時所', 'cmtDate': '2023-05-07 02:16:00'}
{'cmtStatus': '→', 'cmtPoster': 'debby1993', 'cmtContent': ':以只能直接取消？（待專業人士補充', 'cmtDate': '2023-05-07 02:16:00'}
{'cmtStatus': '推', 'cmtPoster': 'Subscript9', 'cmtContent': ':直接被洞八…', 'cmtDate': '2023-05-07 02:17:00'}
{'cmtStatus': '推', 'cmtPoster': 'shlee', 'cmtContent': ':800從名古屋回到成田的時候已經日本時間晚上7點多', 'cmtDate': '2023-05-07 02:18:00'}
{'cmtStatus': '→', 'cmtPoster': 'shlee', 'cmtContent': ':了那時候801的旅客應該早就跑完轉簽跟併班的手續', 'cmtDate': '2023-05-07 02:18:00'}
{'cmtStatus': '→', 'cmtPoster': 'shlee', 'cmtContent': ':在803上面', 'cmtDate': '2023-05-07 02:18:00'}
{'cmtStatus': '推', 'cmtPoster': 'debby1993', 'cmtContent': ':801就是沒飛機來所以直接取消，那02也不早點取消讓', 'cmtDate': '2023-05-07 02:22:00'}
{'cmtStatus': '→', 'cmtPoster': 'debby1993', 'cmtContent': ':其他人轉簽去另外兩家，那兩家都飛了才說要取消，真', 'cmtDate': '2023-05-07 02:22:00'}
{'cmtStatus': '→', 'cmtPoster': 'debby1993', 'cmtContent': ':的是史詩級災難……', 'cmtDate': '2023-05-07 02:22:00'}
{'cmtStatus': '→', 'cmtPoster': 'UncleRed', 'cmtContent': ':就算那兩家還沒飛也沒位置吧，等下轉不完被說大小眼', 'cmtDate': '2023-05-07 02:24:00'}
{'cmtStatus': '推', 'cmtPoster': 'benson1613', 'cmtContent': ':這真的超級大出事,好久沒有這樣追航空八點檔了哈哈', 'cmtDate': '2023-05-07 02:24:00'}
{'cmtStatus': '推', 'cmtPoster': 'mithralin', 'cmtContent': ':801團客全轉簽其他航空公司，散客改搭803', 'cmtDate': '2023-05-07 02:26:00'}
{'cmtStatus': '推', 'cmtPoster': 'pimachu', 'cmtContent': ':看其他公司要不要出手救援不然這粽子串不完', 'cmtDate': '2023-05-07 02:27:00'}
{'cmtStatus': '推', 'cmtPoster': 'marunouchi', 'cmtContent': ':等著看TPE跟LAX', 'cmtDate': '2023-05-07 02:27:00'}
{'cmtStatus': '推', 'cmtPoster': 'debby1993', 'cmtContent': ':不幫轉還是有少數人會直接當場買別家飛過去，都不給', 'cmtDate': '2023-05-07 02:28:00'}
{'cmtStatus': '→', 'cmtPoster': 'debby1993', 'cmtContent': ':人應變時間的真的糟……', 'cmtDate': '2023-05-07 02:28:00'}
{'cmtStatus': '推', 'cmtPoster': 'mithralin', 'cmtContent': ':這次事件應該可以寫入教科書了，負面教材方面的', 'cmtDate': '2023-05-07 02:29:00'}
{'cmtStatus': '推', 'cmtPoster': 'umyiwen', 'cmtContent': ':有夠大包', 'cmtDate': '2023-05-07 02:31:00'}
{'cmtStatus': '推', 'cmtPoster': 'marunouchi', 'cmtContent': ':後面一串粽子', 'cmtDate': '2023-05-07 02:31:00'}
{'cmtStatus': '推', 'cmtPoster': 'gtayu', 'cmtContent': ':辛苦了', 'cmtDate': '2023-05-07 02:33:00'}
{'cmtStatus': '推', 'cmtPoster': 'ORIENT0510', 'cmtContent': ':究竟是會變成公關的災難還是業界的笑話？', 'cmtDate': '2023-05-07 02:33:00'}
{'cmtStatus': '推', 'cmtPoster': 'roger61212', 'cmtContent': ':如果當下聯絡其他航空業者支援疏散會不會比較好，雖', 'cmtDate': '2023-05-07 02:36:00'}
{'cmtStatus': '→', 'cmtPoster': 'roger61212', 'cmtContent': ':然重拿行李跟登入也是需要不少時間', 'cmtDate': '2023-05-07 02:36:00'}
{'cmtStatus': '→', 'cmtPoster': 'shlee', 'cmtContent': ':要看其他航空公司的航班時間跟有沒有位置', 'cmtDate': '2023-05-07 02:37:00'}
{'cmtStatus': '→', 'cmtPoster': 'shlee', 'cmtContent': ':801是有轉簽團客跟少部分散客給華航也有飛回來然', 'cmtDate': '2023-05-07 02:38:00'}
{'cmtStatus': '→', 'cmtPoster': 'shlee', 'cmtContent': ':後剩餘的散客被安排搭803', 'cmtDate': '2023-05-07 02:38:00'}
{'cmtStatus': '推', 'cmtPoster': 'tookbon', 'cmtContent': ':老實說成田這個風寧可今天不飛命要緊但星宇處理', 'cmtDate': '2023-05-07 02:41:00'}
{'cmtStatus': '→', 'cmtPoster': 'tookbon', 'cmtContent': ':要更完整', 'cmtDate': '2023-05-07 02:41:00'}
{'cmtStatus': '→', 'cmtPoster': 'a27281591', 'cmtContent': ':也要別家有人有時間接', 'cmtDate': '2023-05-07 02:42:00'}
{'cmtStatus': '→', 'cmtPoster': 'a27281591', 'cmtContent': ':還好這不是在超級旺季發生否則更可怕...', 'cmtDate': '2023-05-07 02:43:00'}
{'cmtStatus': '推', 'cmtPoster': 'pimachu', 'cmtContent': ':問題就是你團客都能轉了啊不整機轉掉', 'cmtDate': '2023-05-07 02:44:00'}
{'cmtStatus': '推', 'cmtPoster': 'jakert123', 'cmtContent': ':感覺就是散客改搭803造成的，當初全部轉簽就沒事了', 'cmtDate': '2023-05-07 02:45:00'}
{'cmtStatus': '→', 'cmtPoster': 'jakert123', 'cmtContent': ':，併班導致後面全部gg', 'cmtDate': '2023-05-07 02:45:00'}
{'cmtStatus': '→', 'cmtPoster': 'wisteriachi', 'cmtContent': ':只有800跟成田風有關係，後續一連串是星宇調度問題', 'cmtDate': '2023-05-07 02:46:00'}
{'cmtStatus': '→', 'cmtPoster': 'wisteriachi', 'cmtContent': ':。', 'cmtDate': '2023-05-07 02:46:00'}
{'cmtStatus': '推', 'cmtPoster': 'mithralin', 'cmtContent': ':轉簽也要其他航班飛機有空位，現在還在黃金週加上', 'cmtDate': '2023-05-07 02:49:00'}
{'cmtStatus': '→', 'cmtPoster': 'mithralin', 'cmtContent': ':假日位置本來就不多了', 'cmtDate': '2023-05-07 02:49:00'}
{'cmtStatus': '→', 'cmtPoster': 'autumoon', 'cmtContent': ':我樂桃被關四小時那次有人直接去敲機長室的門抗議', 'cmtDate': '2023-05-07 02:50:00'}
{'cmtStatus': '推', 'cmtPoster': 'suba1121', 'cmtContent': ':推很精闢的懶人包連轉簽的801行李狀況都有', 'cmtDate': '2023-05-07 02:51:00'}
{'cmtStatus': '→', 'cmtPoster': 'sinohara', 'cmtContent': ':以前的強側風重落地在NH還是767老飛機的時代也有過', 'cmtDate': '2023-05-07 02:51:00'}
{'cmtStatus': '推', 'cmtPoster': 'huang19898', 'cmtContent': ':如果暴動有沒機會下飛機?認賠刷機場住宿+第二天他', 'cmtDate': '2023-05-07 02:54:00'}
{'cmtStatus': '→', 'cmtPoster': 'huang19898', 'cmtContent': ':家廉航機票也遠比關飛機上8個小時好', 'cmtDate': '2023-05-07 02:55:00'}
{'cmtStatus': '推', 'cmtPoster': 'mithralin', 'cmtContent': ':沒有機會，因為過宵禁時間人家都下班了', 'cmtDate': '2023-05-07 02:55:00'}
{'cmtStatus': '推', 'cmtPoster': 'MTBF', 'cmtContent': ':精簡客觀', 'cmtDate': '2023-05-07 02:55:00'}
{'cmtStatus': '→', 'cmtPoster': 'huang19898', 'cmtContent': ':如果9點之類的時間以生病之名要求下機或報警不知可', 'cmtDate': '2023-05-07 02:58:00'}
{'cmtStatus': '→', 'cmtPoster': 'huang19898', 'cmtContent': ':不可行', 'cmtDate': '2023-05-07 02:58:00'}
{'cmtStatus': '推', 'cmtPoster': 'jasonchiu122', 'cmtContent': ':看FB旅客的最新回報，現在都獲得成田候機室地板體', 'cmtDate': '2023-05-07 02:59:00'}
{'cmtStatus': '→', 'cmtPoster': 'jasonchiu122', 'cmtContent': ':驗券一張', 'cmtDate': '2023-05-07 02:59:00'}
{'cmtStatus': '→', 'cmtPoster': 'autumoon', 'cmtContent': ':如果是119或110的方式出艙門的話後果應該滿有趣的..', 'cmtDate': '2023-05-07 02:59:00'}
{'cmtStatus': '→', 'cmtPoster': 'autumoon', 'cmtContent': ':因為不是台灣，是日本。是成田機場不是成田車站。', 'cmtDate': '2023-05-07 03:00:00'}
{'cmtStatus': '→', 'cmtPoster': 'er5820', 'cmtContent': ':社團桃園飛美國罵聲連連有給飯店4人一間只有30個房', 'cmtDate': '2023-05-07 03:02:00'}
{'cmtStatus': '→', 'cmtPoster': 'er5820', 'cmtContent': ':間', 'cmtDate': '2023-05-07 03:02:00'}
{'cmtStatus': '推', 'cmtPoster': 'phoebe147', 'cmtContent': ':臉書一堆看不懂新聞再罵乘客的，哭啊', 'cmtDate': '2023-05-07 03:06:00'}
{'cmtStatus': '推', 'cmtPoster': 'huang19898', 'cmtContent': ':110或119的方式出艙門會違反飛安法嗎?', 'cmtDate': '2023-05-07 03:14:00'}
{'cmtStatus': '推', 'cmtPoster': 'S890127', 'cmtContent': ':早上那個強風轉降還算是情有可原，安全要緊', 'cmtDate': '2023-05-07 03:14:00'}
{'cmtStatus': '→', 'cmtPoster': 'S890127', 'cmtContent': ':那時候怪星宇沒道理但後面調度處理太糟糕了', 'cmtDate': '2023-05-07 03:15:00'}
{'cmtStatus': '→', 'cmtPoster': 'TheoEpstein', 'cmtContent': ':推一個懶人包', 'cmtDate': '2023-05-07 03:16:00'}
{'cmtStatus': '→', 'cmtPoster': 'S890127', 'cmtContent': ':這個只有賠機票錢根本不夠', 'cmtDate': '2023-05-07 03:16:00'}
{'cmtStatus': '→', 'cmtPoster': 'S890127', 'cmtContent': ':行程延誤大亂還被關在飛機上最後睡機場地板', 'cmtDate': '2023-05-07 03:16:00'}
{'cmtStatus': '→', 'cmtPoster': 'autumoon', 'cmtContent': ':對阿，有保不便險的人虧大了....', 'cmtDate': '2023-05-07 03:18:00'}
{'cmtStatus': '→', 'cmtPoster': 'autumoon', 'cmtContent': ':有沒有違反飛安法不知道，但在機場謊報應該很刺激', 'cmtDate': '2023-05-07 03:19:00'}
{'cmtStatus': '→', 'cmtPoster': 'autumoon', 'cmtContent': ':我去年在沖繩看到有人倒路邊沒確認就打110，警察來', 'cmtDate': '2023-05-07 03:20:00'}
{'cmtStatus': '→', 'cmtPoster': 'autumoon', 'cmtContent': ':了之後看到是爛醉就唸了我一下要我先確認再打電話..', 'cmtDate': '2023-05-07 03:21:00'}
{'cmtStatus': '推', 'cmtPoster': 'TheoEpstein', 'cmtContent': ':現在就退不了關了', 'cmtDate': '2023-05-07 03:23:00'}
{'cmtStatus': '推', 'cmtPoster': 'yanwu0105', 'cmtContent': ':18年也有遇到成田宵禁但捷星有讓我們退關補償全額', 'cmtDate': '2023-05-07 03:40:00'}
{'cmtStatus': '→', 'cmtPoster': 'yanwu0105', 'cmtContent': ':食物計程車飯店費隔天原機飛回台灣', 'cmtDate': '2023-05-07 03:40:00'}
{'cmtStatus': '推', 'cmtPoster': 'chewthelife8', 'cmtContent': ':真的是直接被洞八….當過兵的都知道洞八的痛苦', 'cmtDate': '2023-05-07 03:48:00'}
{'cmtStatus': '→', 'cmtPoster': 'yaoilot', 'cmtContent': ':疫情前酷航高雄飛機壞了，過宵禁還是有退關送去旅館', 'cmtDate': '2023-05-07 03:51:00'}
{'cmtStatus': '→', 'cmtPoster': 'yaoilot', 'cmtContent': ':，所以日本那邊移民署跟海關是時間到準時打卡下班', 'cmtDate': '2023-05-07 03:51:00'}
{'cmtStatus': '→', 'cmtPoster': 'yaoilot', 'cmtContent': ':嗎？', 'cmtDate': '2023-05-07 03:51:00'}
{'cmtStatus': '推', 'cmtPoster': 'lovejay52012', 'cmtContent': ':誰會幫他們家啊............', 'cmtDate': '2023-05-07 03:51:00'}
{'cmtStatus': '→', 'cmtPoster': 'er5820', 'cmtContent': ':酷航是大阪機場是24小時影藝跟成田不一樣', 'cmtDate': '2023-05-07 03:53:00'}
{'cmtStatus': '推', 'cmtPoster': 'MTBF', 'cmtContent': ':是成田宵禁關場移民官海關就下班', 'cmtDate': '2023-05-07 03:54:00'}
{'cmtStatus': '→', 'cmtPoster': 'MTBF', 'cmtContent': ':捷星有辦法協調退關是他們有本事', 'cmtDate': '2023-05-07 03:54:00'}
{'cmtStatus': '→', 'cmtPoster': 'autumoon', 'cmtContent': ':記得捷星後台是JAL，可能是本國班機比較好處理？', 'cmtDate': '2023-05-07 03:59:00'}
{'cmtStatus': '→', 'cmtPoster': 'carolyntsai', 'cmtContent': ':跟主不主場有關係嗎?', 'cmtDate': '2023-05-07 03:59:00'}
{'cmtStatus': '→', 'cmtPoster': 'carolyntsai', 'cmtContent': ':我是想問,是不是跟主場也有關係?', 'cmtDate': '2023-05-07 04:01:00'}
{'cmtStatus': '→', 'cmtPoster': 'autumoon', 'cmtContent': ':我覺得有可能，我幾年前搭往高雄的樂桃因故降落桃園', 'cmtDate': '2023-05-07 04:01:00'}
{'cmtStatus': '→', 'cmtPoster': 'autumoon', 'cmtContent': ':出不去也是因為飛機國籍問題', 'cmtDate': '2023-05-07 04:01:00'}
{'cmtStatus': '推', 'cmtPoster': 'Misako', 'cmtContent': ':調度問題吧危機處理很差，講真的飛不了早點出來說明', 'cmtDate': '2023-05-07 04:11:00'}
{'cmtStatus': '→', 'cmtPoster': 'Misako', 'cmtContent': ':或安排乘客下機休息也好過現在這樣，根本是最爛的處', 'cmtDate': '2023-05-07 04:11:00'}
{'cmtStatus': '→', 'cmtPoster': 'Misako', 'cmtContent': ':理方式', 'cmtDate': '2023-05-07 04:11:00'}
{'cmtStatus': '推', 'cmtPoster': 'cching1021', 'cmtContent': ':801轉簽轉不了的直接送旅館讓803自己正常起飛就', 'cmtDate': '2023-05-07 04:13:00'}
{'cmtStatus': '→', 'cmtPoster': 'cching1021', 'cmtContent': ':什麼事都不會有', 'cmtDate': '2023-05-07 04:13:00'}
{'cmtStatus': '推', 'cmtPoster': 'asdfgh369', 'cmtContent': ':801跟803的大大們都辛苦了...這處理真的太誇張', 'cmtDate': '2023-05-07 04:17:00'}
{'cmtStatus': '推', 'cmtPoster': 'tprktpps', 'cmtContent': ':星宇調度真的爛不應該併班就算了機組人員超時時', 'cmtDate': '2023-05-07 04:48:00'}
{'cmtStatus': '→', 'cmtPoster': 'tprktpps', 'cmtContent': ':也早該放人下機想也知道今天肯定無法起飛了高層', 'cmtDate': '2023-05-07 04:48:00'}
{'cmtStatus': '→', 'cmtPoster': 'tprktpps', 'cmtContent': ':真的有病', 'cmtDate': '2023-05-07 04:48:00'}
{'cmtStatus': '推', 'cmtPoster': 'gm3252', 'cmtContent': ':旅客這麼生氣還有一點是是被關在飛機上太久，早點', 'cmtDate': '2023-05-07 05:31:00'}
{'cmtStatus': '→', 'cmtPoster': 'gm3252', 'cmtContent': ':放人到機場還不會這麼嚴重', 'cmtDate': '2023-05-07 05:31:00'}
{'cmtStatus': '推', 'cmtPoster': 'encorea84459', 'cmtContent': ':而且8點那時說要延到11點就有乘客反應宵禁問題了', 'cmtDate': '2023-05-07 05:33:00'}
{'cmtStatus': '→', 'cmtPoster': 'encorea84459', 'cmtContent': ':完全不管硬要賭真的是扯爛', 'cmtDate': '2023-05-07 05:33:00'}
{'cmtStatus': '推', 'cmtPoster': 'Taku1003', 'cmtContent': ':原801乘客淚推…為什麼不把我轉簽出去', 'cmtDate': '2023-05-07 05:48:00'}
{'cmtStatus': '推', 'cmtPoster': 'darrenh', 'cmtContent': ':所以jx2有飛嗎？', 'cmtDate': '2023-05-07 05:48:00'}
{'cmtStatus': '推', 'cmtPoster': 'naoko10078', 'cmtContent': ':搭今天800的瑟瑟發抖', 'cmtDate': '2023-05-07 05:51:00'}
{'cmtStatus': '推', 'cmtPoster': 'darrenh', 'cmtContent': ':樓上應該已經在機場了吧？有飛？', 'cmtDate': '2023-05-07 05:58:00'}
{'cmtStatus': '推', 'cmtPoster': 'naoko10078', 'cmtContent': ':前往機場路上', 'cmtDate': '2023-05-07 06:02:00'}
{'cmtStatus': '推', 'cmtPoster': 'darrenh', 'cmtContent': ':今天到底有沒有飛機可以飛800，我看桃機寫正常', 'cmtDate': '2023-05-07 06:03:00'}
{'cmtStatus': '推', 'cmtPoster': 'naoko10078', 'cmtContent': ':看星宇網站動態也都是正常', 'cmtDate': '2023-05-07 06:05:00'}
{'cmtStatus': '推', 'cmtPoster': 'nolimits', 'cmtContent': ':虎航也有飛成田的吧怎麼就沒有問題？', 'cmtDate': '2023-05-07 06:18:00'}
{'cmtStatus': '推', 'cmtPoster': 'Vladivostok', 'cmtContent': ':要是其他兩家這樣應該幹譙到翻了吧', 'cmtDate': '2023-05-07 06:20:00'}
{'cmtStatus': '推', 'cmtPoster': 'naoko10078', 'cmtContent': ':看起來今早800是正常', 'cmtDate': '2023-05-07 06:28:00'}
{'cmtStatus': '推', 'cmtPoster': 'TT', 'cmtContent': ':昨天正好是延遲一下起飛的CI103，風超大超晃', 'cmtDate': '2023-05-07 06:29:00'}
{'cmtStatus': '→', 'cmtPoster': 'TT', 'cmtContent': ':主要看起來是後續處理的太糟，好險都平安', 'cmtDate': '2023-05-07 06:30:00'}
{'cmtStatus': '推', 'cmtPoster': 'zxc11234', 'cmtContent': ':天氣因素的話也沒什麼好說的，但很明顯就是星宇完', 'cmtDate': '2023-05-07 06:32:00'}
{'cmtStatus': '→', 'cmtPoster': 'zxc11234', 'cmtContent': ':全沒有危機處理能力，一個大風就把問題吹出來，以', 'cmtDate': '2023-05-07 06:32:00'}
{'cmtStatus': '→', 'cmtPoster': 'zxc11234', 'cmtContent': ':後直接列入黑名單了，我猜補償應該會很豐厚不然壓', 'cmtDate': '2023-05-07 06:32:00'}
{'cmtStatus': '→', 'cmtPoster': 'zxc11234', 'cmtContent': ':不下來', 'cmtDate': '2023-05-07 06:32:00'}
{'cmtStatus': '→', 'cmtPoster': 'lcchang', 'cmtContent': ':目前日本時間07:38，還在成田躺睡袋還沒有任何登機', 'cmtDate': '2023-05-07 06:39:00'}
{'cmtStatus': '→', 'cmtPoster': 'lcchang', 'cmtContent': ':消息', 'cmtDate': '2023-05-07 06:39:00'}
{'cmtStatus': '→', 'cmtPoster': 'encorea84459', 'cmtContent': ':是我沒睡醒還是怎樣剛說要拆三班？', 'cmtDate': '2023-05-07 06:43:00'}
{'cmtStatus': '推', 'cmtPoster': 'S890127', 'cmtContent': ':話說如果有人買要冰的土產(Royce之類)不就報銷了', 'cmtDate': '2023-05-07 07:12:00'}
{'cmtStatus': '→', 'cmtPoster': 'S890127', 'cmtContent': ':雖然這相較之下沒那麼重要了', 'cmtDate': '2023-05-07 07:12:00'}
{'cmtStatus': '推', 'cmtPoster': 'jtsu5223', 'cmtContent': ':好慘', 'cmtDate': '2023-05-07 07:15:00'}
{'cmtStatus': '推', 'cmtPoster': 'Yumon', 'cmtContent': ':要冰的土產可能就打開吃了吧', 'cmtDate': '2023-05-07 07:16:00'}
{'cmtStatus': '推', 'cmtPoster': 'TT', 'cmtContent': ':這有買旅平險應該能利用到，沒買就真的慘', 'cmtDate': '2023-05-07 07:20:00'}
{'cmtStatus': '推', 'cmtPoster': 'nuc1earsub', 'cmtContent': ':董欸不是去現場了?', 'cmtDate': '2023-05-07 07:23:00'}
{'cmtStatus': '→', 'cmtPoster': 'autumoon', 'cmtContent': ':這次的狀況是不便險的賠償範圍吧？', 'cmtDate': '2023-05-07 07:25:00'}
{'cmtStatus': '推', 'cmtPoster': 'kenploin', 'cmtContent': ':這家這樣搞絕對不搭呀處理很糟糕', 'cmtDate': '2023-05-07 07:35:00'}
{'cmtStatus': '推', 'cmtPoster': 'inewhand', 'cmtContent': ':兩班乘客跟機組都辛苦了，卡一個等後續', 'cmtDate': '2023-05-07 07:42:00'}
{'cmtStatus': '→', 'cmtPoster': 'autumoon', 'cmtContent': ':剛想到星宇這樣搞，不便險的理賠金額可能也不太樂觀', 'cmtDate': '2023-05-07 07:52:00'}
{'cmtStatus': '推', 'cmtPoster': 'applebob', 'cmtContent': ':明天要飛怕...', 'cmtDate': '2023-05-07 07:56:00'}
{'cmtStatus': '推', 'cmtPoster': 'TT', 'cmtContent': ':就超過四小時+行程延誤這兩款項能領吧', 'cmtDate': '2023-05-07 07:56:00'}
{'cmtStatus': '→', 'cmtPoster': 'chie24', 'cmtContent': ':行李延誤要看有的回國段不賠……', 'cmtDate': '2023-05-07 08:01:00'}
{'cmtStatus': '→', 'cmtPoster': 'autumoon', 'cmtContent': ':我之前搭樂桃沖繩高雄沖繩的環線班機申請理賠時弄很', 'cmtDate': '2023-05-07 08:02:00'}
{'cmtStatus': '→', 'cmtPoster': 'autumoon', 'cmtContent': ':久，而且同班機專員的判斷居然不一樣害我少領一筆', 'cmtDate': '2023-05-07 08:03:00'}
{'cmtStatus': '推', 'cmtPoster': 'Bokaka', 'cmtContent': ':航空板說k董還得幫忙開飛機回來XD', 'cmtDate': '2023-05-07 08:03:00'}
{'cmtStatus': '→', 'cmtPoster': 'autumoon', 'cmtContent': ':星宇這趟最想哭的應該是沒有「過夜補助」', 'cmtDate': '2023-05-07 08:04:00'}
{'cmtStatus': '→', 'cmtPoster': 'chie24', 'cmtContent': ':用睡袋換滯留旅客住宿費用賺爛，我說星宇賺爛', 'cmtDate': '2023-05-07 08:07:00'}
{'cmtStatus': '推', 'cmtPoster': 'TT', 'cmtContent': ':新企畫夜宿成田機場(無料)', 'cmtDate': '2023-05-07 08:10:00'}
{'cmtStatus': '推', 'cmtPoster': 'greenfetish', 'cmtContent': ':所以被關在機上多久啊？待候機室我能忍，被關機上', 'cmtDate': '2023-05-07 08:23:00'}
{'cmtStatus': '→', 'cmtPoster': 'greenfetish', 'cmtContent': ':那小空間真心不能忍', 'cmtDate': '2023-05-07 08:23:00'}
{'cmtStatus': '推', 'cmtPoster': 'Serio', 'cmtContent': ':行李延誤要看保險怎寫之前我PEK-TPE行李沒上飛機', 'cmtDate': '2023-05-07 08:27:00'}
{'cmtStatus': '→', 'cmtPoster': 'Serio', 'cmtContent': ':最後也沒賠(因為已經回國沒有影響衣住等)', 'cmtDate': '2023-05-07 08:28:00'}
{'cmtStatus': '→', 'cmtPoster': 'Serio', 'cmtContent': ':行程延誤這應該算人為非天候(大雪)應該有辦法拿', 'cmtDate': '2023-05-07 08:29:00'}
{'cmtStatus': '推', 'cmtPoster': 'IUOIUOIUO', 'cmtContent': ':開始需要看這次事件哪些保險有賠了感覺沒那麼簡單', 'cmtDate': '2023-05-07 08:30:00'}
{'cmtStatus': '→', 'cmtPoster': 'w2776803', 'cmtContent': ':這個人為疏失居多吧換成自己被關在機上，機組員只會', 'cmtDate': '2023-05-07 08:33:00'}
{'cmtStatus': '→', 'cmtPoster': 'w2776803', 'cmtContent': ':說等，雖然基層無辜，但旅客生氣也正常', 'cmtDate': '2023-05-07 08:33:00'}
{'cmtStatus': '推', 'cmtPoster': 'BNT5566', 'cmtContent': ':關在機上7小時啦18-01', 'cmtDate': '2023-05-07 08:44:00'}
{'cmtStatus': '→', 'cmtPoster': 'BNT5566', 'cmtContent': ':重點過程中沒持續更新消息，導致大家都不知在等啥', 'cmtDate': '2023-05-07 08:45:00'}
{'cmtStatus': '→', 'cmtPoster': 'alwayspink', 'cmtContent': ':樓上那真的會很無力無助', 'cmtDate': '2023-05-07 08:47:00'}
{'cmtStatus': '→', 'cmtPoster': 'IUOIUOIUO', 'cmtContent': ':機上關玩換關機場總共到底多久800跟803', 'cmtDate': '2023-05-07 08:48:00'}
{'cmtStatus': '推', 'cmtPoster': 'kwinner', 'cmtContent': ':長榮和華航會怎麼處理？', 'cmtDate': '2023-05-07 08:49:00'}
{'cmtStatus': '→', 'cmtPoster': 'IUOIUOIUO', 'cmtContent': ':長榮一開始就會降落成功華航會一堆飛機載人回來', 'cmtDate': '2023-05-07 08:50:00'}
{'cmtStatus': '→', 'cmtPoster': 'kwinner', 'cmtContent': ':誰在乎飛機駕駛是誰？什麼飛才是重點行李、住宿、', 'cmtDate': '2023-05-07 08:51:00'}
{'cmtStatus': '→', 'cmtPoster': 'kwinner', 'cmtContent': ':餐點', 'cmtDate': '2023-05-07 08:51:00'}
{'cmtStatus': '推', 'cmtPoster': 'foreverfree', 'cmtContent': ':調度真的雷，廉航都沒看過這麼大的包', 'cmtDate': '2023-05-07 08:51:00'}
{'cmtStatus': '→', 'cmtPoster': 'autumoon', 'cmtContent': ':在這之前我以為我被樂桃關艙四小時重返原地已經夠慘', 'cmtDate': '2023-05-07 08:52:00'}
{'cmtStatus': '→', 'cmtPoster': 'chinick1478', 'cmtContent': ':今天801也延誤囉～', 'cmtDate': '2023-05-07 08:53:00'}
{'cmtStatus': '推', 'cmtPoster': 'cmelo1515', 'cmtContent': ':800的乘客張董會給壓驚補貼嗎', 'cmtDate': '2023-05-07 08:59:00'}
{'cmtStatus': '推', 'cmtPoster': 'vashwu', 'cmtContent': ':沒事啦再找兩個網紅開箱經濟艙餐點就好', 'cmtDate': '2023-05-07 09:04:00'}
{'cmtStatus': '推', 'cmtPoster': 'IUOIUOIUO', 'cmtContent': ':順便推出800特調803特調期間限定', 'cmtDate': '2023-05-07 09:05:00'}
{'cmtStatus': '推', 'cmtPoster': 'Jelen', 'cmtContent': ':辛苦旅客了', 'cmtDate': '2023-05-07 09:07:00'}
{'cmtStatus': '推', 'cmtPoster': 's91ad017', 'cmtContent': ':申請理賠看起來可以選班機延誤，本來還可以選旅遊', 'cmtDate': '2023-05-07 09:11:00'}
{'cmtStatus': '→', 'cmtPoster': 's91ad017', 'cmtContent': ':更改(但因為沒有住宿交通的費用，睡機場)', 'cmtDate': '2023-05-07 09:11:00'}
{'cmtStatus': '推', 'cmtPoster': 'n196t', 'cmtContent': ':調度雷暴', 'cmtDate': '2023-05-07 09:13:00'}
{'cmtStatus': '推', 'cmtPoster': 'willieliu', 'cmtContent': ':推精品廉航', 'cmtDate': '2023-05-07 09:13:00'}
{'cmtStatus': '→', 'cmtPoster': 'kiromomo168', 'cmtContent': ':退機票以外也要給補償金吧，人家都被困在飛機上好幾', 'cmtDate': '2023-05-07 09:14:00'}
{'cmtStatus': '→', 'cmtPoster': 'kiromomo168', 'cmtContent': ':個小時還被迫睡機場地板', 'cmtDate': '2023-05-07 09:14:00'}
{'cmtStatus': '推', 'cmtPoster': 'kadolong', 'cmtContent': ':張董親自道歉又有消息全退了好了啦', 'cmtDate': '2023-05-07 09:15:00'}
{'cmtStatus': '推', 'cmtPoster': 'kadolong', 'cmtContent': ':還要貪補償金咧這樣算時薪300好了', 'cmtDate': '2023-05-07 09:17:00'}
{'cmtStatus': '推', 'cmtPoster': 'wlmily', 'cmtContent': ':全退是應該的好嗎？', 'cmtDate': '2023-05-07 09:17:00'}
{'cmtStatus': '→', 'cmtPoster': 'adort', 'cmtContent': ':兩架在成田只有一班要載客回來嗎', 'cmtDate': '2023-05-07 09:18:00'}

In [ ]:
#首先我們在經過資料前處理後，將資料整理成方便分析的格式

In [102]:
raw_data = raw_data.explode(['artComter','artStatus'])
social_data = raw_data[['artUrl','artPoster','artComter','artStatus']]
social_data.head(10)

,artUrl,artPoster,artComter,artStatus
36,https://www.ptt.cc/bbs/Japan_Travel/M.16833962...,UncleRed,chen210121,推
36,https://www.ptt.cc/bbs/Japan_Travel/M.16833962...,UncleRed,kyonyuumania,推
36,https://www.ptt.cc/bbs/Japan_Travel/M.16833962...,UncleRed,debby1993,推
36,https://www.ptt.cc/bbs/Japan_Travel/M.16833962...,UncleRed,soulXdancer,→
36,https://www.ptt.cc/bbs/Japan_Travel/M.16833962...,UncleRed,shlee,→
36,https://www.ptt.cc/bbs/Japan_Travel/M.16833962...,UncleRed,YYZZKK,推
36,https://www.ptt.cc/bbs/Japan_Travel/M.16833962...,UncleRed,mithralin,推
36,https://www.ptt.cc/bbs/Japan_Travel/M.16833962...,UncleRed,mithralin,推
36,https://www.ptt.cc/bbs/Japan_Travel/M.16833962...,UncleRed,purevision,推
36,https://www.ptt.cc/bbs/Japan_Travel/M.16833962...,UncleRed,er5820,→

In [103]:
#查看資料集的推文狀況，可以看到有推有噓也有箭頭
social_data.artStatus.unique()

array(['推', '→', '噓'], dtype=object)

接著劃分發文、跟回覆，建立網路圖

In [104]:
# 建立邊的資料
import random


po_df = social_data[['artPoster','artUrl']].drop_duplicates().rename(columns = {'artPoster':'src','artUrl':'dis'})
sample_url = random.choices(po_df.dis.unique().tolist(),k=300)
po_df = po_df[po_df.dis.isin(sample_url)]
re_df = social_data[['artComter','artUrl','artStatus']].rename(columns = {'artComter':'src','artUrl':'dis','artStatus':'weight'})
re_df = re_df[re_df.dis.isin(sample_url)]
re_df = re_df[~re_df['src'].isna()]



def convertStatus(s):
  if s == '推':
    return 2
  elif s == '→':
    return 1
  else :
    return -1
re_df['weight'] = re_df['weight'].map(convertStatus)
re_df = re_df.groupby(['src','dis']).sum().reset_index()

# 設定分數低的為紅色
def getColor(w):
  if w>0:
    return 'green'
  else:
    return 'red'
re_df['color'] = re_df.weight.map(getColor)

In [134]:
# 人為綠色節點
# po文為橘色節點

netWork = pyvis.network.Network(notebook=True, cdn_resources='in_line',directed=True)
person = list(set(po_df.src.unique().tolist()+re_df.src.unique().tolist()))
url = po_df.dis.unique().tolist()
netWork.add_nodes(
    nodes = person,
    value = [1 for i in range(len(person))],
    color = ['#66CDAA' for i in range(len(person))],
    title = person
)
netWork.add_nodes(
    nodes = url,
    value = [2 for i in range(len(url))],
    color = ['#FFB366' for i in range(len(url))],
    title = url
)
for i in po_df.to_numpy():
  netWork.add_edge(i[0],i[1],width = 2,color='grey')
for i in re_df.to_numpy():
  netWork.add_edge(i[0],i[1],width = 2,color=i[3])

# 設定layout
netWork.repulsion()

netWork.toggle_physics(False)
netWork.set_options("""
const options = {
  "physics": {
    "forceAtlas2Based": {
      "springLength": 100
    },
    "minVelocity": 0.75,
    "solver": "forceAtlas2Based",
    "timestep": 0.48
  }
}
""")

netWork.show("./basic_netWork.html")
IPython.display.HTML('basic_netWork.html')

./basic_netWork.html

可以看到圖中，將有較多回覆的文拉出來看一下大概是哪類型的文，可以有較多的回覆。
另一方面可以看到在圖上有少數的發文是有紅線的，也將該文拿出來看看是哪種文。

接著簡單看一下哪篇文跟作者的回覆最多

In [107]:
social_data['artUrl'].value_counts()

https://www.ptt.cc/bbs/Japan_Travel/M.1683396221.A.169.html    960
https://www.ptt.cc/bbs/Japan_Travel/M.1683829568.A.6FF.html     65
https://www.ptt.cc/bbs/Japan_Travel/M.1683533701.A.374.html     64
https://www.ptt.cc/bbs/Japan_Travel/M.1684289901.A.336.html     60
https://www.ptt.cc/bbs/Japan_Travel/M.1683457949.A.2D3.html     60
https://www.ptt.cc/bbs/Japan_Travel/M.1684032796.A.1B9.html     48
https://www.ptt.cc/bbs/Japan_Travel/M.1683836664.A.4BC.html     41
https://www.ptt.cc/bbs/Japan_Travel/M.1683526229.A.A21.html     40
https://www.ptt.cc/bbs/Japan_Travel/M.1684215601.A.7E2.html     36
https://www.ptt.cc/bbs/Japan_Travel/M.1683859440.A.3CF.html     35
https://www.ptt.cc/bbs/Japan_Travel/M.1684029778.A.8EC.html     34
https://www.ptt.cc/bbs/Japan_Travel/M.1684254309.A.519.html     27
https://www.ptt.cc/bbs/Japan_Travel/M.1683805781.A.426.html     25
https://www.ptt.cc/bbs/Japan_Travel/M.1684046197.A.496.html     22
https://www.ptt.cc/bbs/Japan_Travel/M.1683557672.A.20C.html     19
https://www.ptt.cc/bbs/Japan_Travel/M.1683210008.A.6AD.html     18
https://www.ptt.cc/bbs/Japan_Travel/M.1683823202.A.296.html     11
https://www.ptt.cc/bbs/Japan_Travel/M.1683386395.A.A11.html     10
https://www.ptt.cc/bbs/Japan_Travel/M.1684587763.A.BE8.html      8
https://www.ptt.cc/bbs/Japan_Travel/M.1684499712.A.4E7.html      8
https://www.ptt.cc/bbs/Japan_Travel/M.1684162487.A.2BE.html      8
https://www.ptt.cc/bbs/Japan_Travel/M.1684535449.A.6B6.html      7
https://www.ptt.cc/bbs/Japan_Travel/M.1684319286.A.A0B.html      7
https://www.ptt.cc/bbs/Japan_Travel/M.1684468573.A.9CC.html      6
https://www.ptt.cc/bbs/Japan_Travel/M.1684300498.A.D56.html      6
https://www.ptt.cc/bbs/Japan_Travel/M.1683045443.A.A37.html      6
https://www.ptt.cc/bbs/Japan_Travel/M.1683277152.A.386.html      4
https://www.ptt.cc/bbs/Japan_Travel/M.1684198206.A.65A.html      4
https://www.ptt.cc/bbs/Japan_Travel/M.1683217157.A.F78.html      4
https://www.ptt.cc/bbs/Japan_Travel/M.1682951703.A.1FC.html      3
https://www.ptt.cc/bbs/Japan_Travel/M.1684512030.A.A9C.html      3
https://www.ptt.cc/bbs/Japan_Travel/M.1684508435.A.D56.html      2
https://www.ptt.cc/bbs/Japan_Travel/M.1683785580.A.7EA.html      2
https://www.ptt.cc/bbs/Japan_Travel/M.1683457974.A.2D4.html      2
https://www.ptt.cc/bbs/Japan_Travel/M.1683564640.A.C62.html      1
https://www.ptt.cc/bbs/Japan_Travel/M.1682933943.A.126.html      1
https://www.ptt.cc/bbs/Japan_Travel/M.1683857141.A.41D.html      1
https://www.ptt.cc/bbs/Japan_Travel/M.1683476665.A.0BE.html      1
Name: artUrl, dtype: int64

In [108]:
social_data['artPoster'].value_counts()

UncleRed        960
OhmoriHarumi    100
kashima228       65
adychen1982      64
xxYAYAxx         60
shinchenboy      48
bababana         41
bluewith         36
yhls             35
shin761124       34
Jamez            27
talon0222        25
bravewarrior     22
legool           19
abnerli          18
JimXpp           12
buaa2211         11
mvpdirk712       10
Aurora5566        8
skw15             8
ihatebbo          8
allen101pq        7
kenploin          6
hesitates         6
rainwing          6
k272821           4
HeSit             4
lsylin            3
jardin123         3
tedandjolin       2
emu200            2
matmoki           2
sleetyarn         1
airpigeon         1
zonapha           1
Name: artPoster, dtype: int64

可以發現，比較多人回覆的貼文大都是日本旅遊板的鄉民幫忙旅遊行程健檢或推薦，以及遊記的分享，會有較多的回覆，且都是箭頭或是推。
最特別的是最多人回覆的那篇，是關於星宇航空最近的新聞的懶人包，該機上乘客對於整起事件的整理，因此關注度最高
而出現噓文的幾篇貼文中，較多回覆的那篇(https://www.ptt.cc/bbs/Japan_Travel/M.1683526229.A.A21.html) 
內容則是分享國泰航空的優惠，但是由於國泰航空是香港的航空公司，有一些鄉民會因為意識型態不同而有不同立場的推文，因此出現了噓文。

而第二篇有噓文的(https://www.ptt.cc/bbs/Japan_Travel/M.1684568147.A.946.html) 文章主要是在問歷年來九月東京的人潮，藉此有個預期心理，但噓文的人認為今年九月還沒到怎麼知道人潮如何而做出噓文，整體來說這篇文是正常的提問，只出現一個噓，可以當作特例。

計算網友之間的關係

In [109]:
pos_cmt = social_data.copy()
pos_cmt = pos_cmt[~pos_cmt.artComter.isna()]
pos_cmt.head(10)

,artUrl,artPoster,artComter,artStatus
36,https://www.ptt.cc/bbs/Japan_Travel/M.16833962...,UncleRed,chen210121,推
36,https://www.ptt.cc/bbs/Japan_Travel/M.16833962...,UncleRed,kyonyuumania,推
36,https://www.ptt.cc/bbs/Japan_Travel/M.16833962...,UncleRed,debby1993,推
36,https://www.ptt.cc/bbs/Japan_Travel/M.16833962...,UncleRed,soulXdancer,→
36,https://www.ptt.cc/bbs/Japan_Travel/M.16833962...,UncleRed,shlee,→
36,https://www.ptt.cc/bbs/Japan_Travel/M.16833962...,UncleRed,YYZZKK,推
36,https://www.ptt.cc/bbs/Japan_Travel/M.16833962...,UncleRed,mithralin,推
36,https://www.ptt.cc/bbs/Japan_Travel/M.16833962...,UncleRed,mithralin,推
36,https://www.ptt.cc/bbs/Japan_Travel/M.16833962...,UncleRed,purevision,推
36,https://www.ptt.cc/bbs/Japan_Travel/M.16833962...,UncleRed,er5820,→

In [110]:
pos_cmt['score'] = pos_cmt['artStatus'].apply(lambda r: convertStatus(r))
pos_cmt = pos_cmt.groupby(['artComter','artPoster']).sum('score').reset_index()
pos_cmt = pos_cmt[pos_cmt.score>=0]
pos_cmt = pos_cmt[pos_cmt.artComter != pos_cmt.artPoster]
# pos_cmt.score = 1
pos_cmt

      artComter     artPoster  score
0     A00610lol      UncleRed      9
1           APC      UncleRed      2
2       Aaron22          yhls      3
3    Abbaschian      xxYAYAxx      2
4    AisinGioro    mvpdirk712      5
..          ...           ...    ...
596    zxc70227        JimXpp      2
597       zzlzz      UncleRed      2
598        zzro  OhmoriHarumi      3
599    zzyyxx77   shinchenboy      1
600    zzzz8931      UncleRed      2

[582 rows x 3 columns]

In [111]:
pers = np.unique(pos_cmt[['artComter', 'artPoster']])
mat = pd.pivot_table(pos_cmt,index = 'artComter', columns = 'artPoster' ,values='score' ).fillna(0)\
  .reindex(columns=pers, index=pers, fill_value=0).to_numpy() #有向
print(mat.shape)
tri = (np.tril(mat,-1).T + np.triu(mat,1))
mat_s = tri+tri.T #無向

(523, 523)

In [112]:
def random_color():
  r = lambda: random.randint(0,255)
  return '#%02X%02X%02X' % (r(),r(),r())

def matPresentGraph(mat:np.array,node_id:list,node_type:list=None,node_value:list = None,directed = True,edge_color=None) -> pyvis.network.Network:

  if directed != True:
    if (mat == mat.transpose()).all():
      print('matrix is Symmetric')
    else:
      print('matrix is not Symmetric')
  if node_type == None:
    c = random_color()
    node_colors = [c for i in range(len(node_id))]
    node_type = [" " for i in range(len(node_id))]
  else:
    node_color_map = {}
    for i in set(node_type):
      while True:
        c = random_color()
        if c not in node_color_map.values():
          break
      node_color_map[i] = c
    node_colors = [node_color_map[i] for i in node_type]
  # print(node_colors)
  if edge_color == None:
    edge_color = random_color()
  edge_color = random_color()
  if node_value == None:
    node_value = [1 for i in range(len(node_id))]

  net = pyvis.network.Network(notebook=True, directed = directed, cdn_resources='in_line')
  
  titles_list = []
  for i ,j in zip(node_id,node_type):
    titles_list.append(str(i)+":"+str(j))

  net.add_nodes(
      nodes = node_id,
      value = node_value,
      label = node_id,
      title = titles_list,
      color = node_colors
  )

  for row in range(len(node_id)):
    for col in range(len(node_id)):
      if mat[row][col]>0.:
        net.add_edge(
            node_id[row],node_id[col],width = mat[row][col],color = edge_color,title = mat[row][col]
        )
  net.repulsion()
  return net

In [113]:
# 定義發文者（po）、評論者(cmt)、兩者兼具(both)
node_type = []

cmt_list = pos_cmt['artComter'].unique().tolist()
po_list = pos_cmt['artPoster'].unique().tolist()
both_list = list(set(cmt_list) & set(po_list))
for p in pers:
  if p in both_list:
    node_type.append('both')

  elif p in cmt_list:
    node_type.append('cmt')

  elif p in po_list:
    node_type.append('po')

In [114]:
net = matPresentGraph(mat = mat,node_id = pers,node_type = node_type)
net.show("./pers_netWork.html")
IPython.display.HTML('pers_netWork.html')

./pers_netWork.html

可以發現回覆的網友最多，其次是發文的，both的網友最少

計算eigenvector centrality （無向圖）

In [115]:
eigenvec = np.array(list(nx.eigenvector_centrality(nx.Graph(mat_s),max_iter = 10000).values()))
eigenvec = (eigenvec-np.min(eigenvec))/(np.max(eigenvec)-np.min(eigenvec))

In [116]:
q = np.quantile(eigenvec,[.2,.4,.6,.8])
q

array([0.000717  , 0.00480973, 0.05876176, 0.05876176])

In [117]:
node_value = []


for i in eigenvec:

  if i > q[3]:
    node_value.append(25)
  elif i >q[2]:
    node_value.append(20)
  elif i>q[1]:
    node_value.append(15)
  elif i>q[0]:
    node_value.append(10)
  else:
    node_value.append(5)
net = matPresentGraph(mat = mat,node_id = pers,node_type = node_type,node_value = node_value,directed=False)
net.show("./pers_eig_netWork.html")
IPython.display.HTML('pers_eig_netWork.html')

matrix is not Symmetric
./pers_eig_netWork.html

可以看到回覆的人數越多，該文的原PO的重要程度越高，而同時有發文也是評論者的人的重要程度也比只有發文或只有回的網友高

PageRank (有向圖)

In [118]:
# Digraph 設定有向圖
pagerank = np.array(list(nx.pagerank(nx.DiGraph(mat)).values()))
# pagerank = (pagerank-np.min(pagerank))/(np.max(pagerank)-np.min(pagerank))
pagerank

array([0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.0018825 , 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00112335, 0.00090733,
       0.01081804, 0.00090733, 0.00810798, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.06987818,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.2485662 , 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.01079968, 0.00090733, 0.00090733,
       0.01476346, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00167882, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00222238, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00299743, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00397354,
       0.00090733, 0.00090733, 0.00090733, 0.00980798, 0.00090733,
       0.00090733, 0.00360367, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00245032, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00418619, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00425967, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00245032, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00245032,
       0.00090733, 0.00090733, 0.00090733, 0.00773294, 0.00090733,
       0.00090733, 0.00245032, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00295007, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00176455, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00245032, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00476482, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00377902, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00710638, 0.00552292, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00158086, 0.00090733, 0.00167882,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.0087362 , 0.00090733, 0.00090733, 0.00167882, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.01545005, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.08226547, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00129308, 0.00090733, 0.00090733, 0.00090733, 0.00090733,
       0.00090733, 0.00090733, 0.00090733])

In [119]:
net = matPresentGraph(mat = mat,node_id = pers,node_type = node_type,node_value=(pagerank*1000).tolist())
net.show("./pers_page_netWork.html")
IPython.display.HTML('pers_page_netWork.html')

./pers_page_netWork.html

可以看出indegree 較多，重要程度愈高，很明顯星宇航空那篇文的作者的分數是最高的

Hits score （有向圖）

In [120]:
out_,in_ = nx.hits(nx.DiGraph(mat),max_iter=100)
out_,in_ = np.array(list(out_.values())),np.array(list(in_.values()))
out_ = (out_-np.min(out_))/(np.max(out_)-np.min(out_))
in_ = (in_-np.min(in_))/(np.max(in_)-np.min(in_))

In [121]:
in_q = np.quantile(in_,[.2,.4,.6,.8])
out_q = np.quantile(out_,[.2,.4,.6,.8])

In [122]:
in_q

array([2.69670641e-17, 2.90774611e-17, 2.99045276e-17, 3.30653254e-17])

In [123]:
node_value = []


for i in out_:
  if i > out_q[3]:
    node_value.append(25)
  elif i >out_q[2]:
    node_value.append(20)
  elif i>out_q[1]:
    node_value.append(15)
  elif i>out_q[0]:
    node_value.append(10)
  else:
    node_value.append(5)

net = matPresentGraph(mat = mat,node_id = pers,node_type = node_type,node_value=node_value)
net.show("./pers_out_netWork.html")
IPython.display.HTML('pers_out_netWork.html')

./pers_out_netWork.html

In [124]:
node_value = []
for i in in_:
  if i > in_q[3]:
    node_value.append(25)
  elif i >in_q[2]:
    node_value.append(20)
  elif i>in_q[1]:
    node_value.append(15)
  elif i>in_q[0]:
    node_value.append(10)
  else:
    node_value.append(5)

net = matPresentGraph(mat = mat,node_id = pers,node_type = node_type,node_value=node_value)
net.show("./pers_in_netWork.html")
IPython.display.HTML('pers_in_netWork.html')

./pers_in_netWork.html

可以發現indegree/outdegree的多寡會決定其重要程度，星宇航空那篇文的作者(UncleRed)的indegree多outdegreeg少，他在關於東京的相關文中，最近只有發這篇文，而且並沒有去回覆他人。

betweenness centrality

In [125]:
bet = np.array(list(nx.betweenness_centrality(nx.Graph(mat_s)).values()))
bet = (bet-np.min(bet))/(np.max(bet)-np.min(bet))
bet_q = np.quantile(bet,[.2,.4,.6,.8])

In [126]:
node_value = []
for i in bet:
  if i > bet_q[3]:
    node_value.append(25)
  elif i > bet_q[2]:
    node_value.append(20)
  elif i>bet_q[1]:
    node_value.append(15)
  elif i>bet_q[0]:
    node_value.append(10)
  else:
    node_value.append(5)

net = matPresentGraph(mat = mat,node_id = pers,node_type = node_type,node_value=node_value)
net.show("./pers_bet_netWork.html")
IPython.display.HTML('pers_bet_netWork.html')

./pers_bet_netWork.html

計算最大的子圖的指標

In [127]:
# 計算max subgraph
G = nx.Graph(mat_s)
G_sub = sorted(nx.connected_components(G), key=len, reverse=True)
G_max_sub = G.subgraph(G_sub[0])
# # 重新定義 mat
sub_mat = nx.adjacency_matrix(G_max_sub).todense()
node_idx = list(G_max_sub.nodes)
sub_pers = pers[node_idx]

畫出最大subgraph

In [128]:
net = matPresentGraph(mat=sub_mat,node_id=sub_pers,directed=False)
net.show("./max_sub.html")
IPython.display.HTML('max_sub.html')

matrix is Symmetric
./max_sub.html

計算transitivity

In [129]:
nx.transitivity(nx.Graph(sub_mat))

0.0006702712364270075

計算density 及 distance

In [130]:
nx.density(nx.Graph(sub_mat))

0.004567728954371389

In [131]:
nx.average_shortest_path_length(nx.Graph(sub_mat))

3.326831959498929

計算diameter

In [132]:
nx.diameter(nx.Graph(sub_mat))

8

計算clustering

In [133]:
nx.average_clustering(nx.Graph(sub_mat))

0.011418563898804333